### ISSUE TITLE
[CLOSED] Document minimal Qt version

### ISSUE THREAD

**Issue by qTox-issue-import** [qTox-issue-import/qTox#70]
<a href="https://github.com/xaizek"><img src="https://avatars.githubusercontent.com/u/459736?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [xaizek](https://github.com/xaizek)**
_2014-07-04, 08:38:44 _
_Originally opened as https://github.com/tux3/qTox/issues/70_

----

Search on GitHub or grepping sources for `Qt5`, `Qt4` or something similar gives no results.

Trying to compile with `Qt 4.8.6`.

```bash
$ qmake
Project MESSAGE: Warning: unknown QT: multimediawidgets
```

```bash
$ make
...
In file included from widget/form/addfriendform.cpp:1:0:
widget/form/addfriendform.h:11:22: fatal error: QDnsLookup: No such file or directory
 #include <QDnsLookup>
...
```

[Official documentation](https://qt-project.org/doc/qt-5/qdnslookup.html) says that `QDnsLookup` is available since `Qt 5.0`.

So *toxgui* seems to require at least `Qt 5.0`, but it's not stated anywhere explicitly.

**Comment by qTox-issue-import** [comment]
<a href="https://github.com/retuxx"><img src="https://avatars.githubusercontent.com/u/317428?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [retuxx](https://github.com/retuxx)**
_2014-07-04, 08:43:28 _

----

By the way, we should also document that this project uses C++-11

**Comment by qTox-issue-import** [comment]
<a href="https://github.com/retuxx"><img src="https://avatars.githubusercontent.com/u/317428?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [retuxx](https://github.com/retuxx)**
_2014-07-04, 09:22:08 _

----

nurupo uses http://pastebin.com/gf8VAPgW to check minimal Qt version

**Comment by qTox-issue-import** [comment]
<a href="https://github.com/tux3"><img src="https://avatars.githubusercontent.com/u/5155966?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tux3](https://github.com/tux3)**
_2014-07-04, 13:35:37 _

----

The minimum required version is Qt 5.2, it might work with Qt 5.0 or 5.1 but I can't guarantee that those versions will still work in the future.

I'll update the README
